export const case_details_form_fields = {
  basic_details: [
    { type: "input", label: "Company Claim No", props: { type: "text", disabled: true }, id: "claim_no" },
    { type: "input", label: "MACT case no:", props: { type: "text", disabled: true }, id: "mact_case_no" },
    { type: "input", label: "Nature Of Loss", props: { type: "text", disabled: true }, id: "type_of_loss" },
    { type: "input", label: "Death/Injury Case of Mr.", props: { type: "text", disabled: true}, id: "injured_name" },
    { type: "input", label: "Mact Court", props: { type: "text", disabled: true }, id: "mapc_cl" },
    { type: "input", label: "Insured Vehicle & registration number", props: { type: "text", disabled: true }, id: "iv_no" },
    { type: "input", label: "Claim Amount", props: { type: "text", disabled: true }, id: "claim_amount" },
    { type: "input", label: "Claim Filled U/s", props: { type: "text", disabled: true }, id: "claim_filled_us" },
    { type: "input", label: "Policy No.", props: { type: "text", disabled: true }, id: "policy_no" },
    { type: "input", label: "Policy Period", props: { type: "text", disabled: true }, id: "policy_end_date" },
    { type: "input", label: "Date of Loss", props: { type: "datetime-local", disabled: true }, id: "date_of_loss" },
    { type: "input", label: "Insured Name", props: { type: "text", disabled: true }, id: "insured" },
    { type: "textarea", label: "Brief of the Case", props: { rows: 2 }, id: "brief_of_the_case" },
    { type: "textarea", label: "Observations", props: { rows: 2}, id: "observations" },
  ],
  JMFC_court_details: [
    { type: "input", label: "Type of case", props: { type: "text"}, id:"case_type" },
    { type: "input", label: "JMFC Case No", props: { type: "text"}, id: "jmfc_case_no" },
    { type: "input", label: "Filling Number ", props: { type: "text",}, id:"filling_no" },
    { type: "input", label: "Registration Number", props: { type: "text"}, id:"registration_number" },
    { type: "input", label: "Registration Date", props: { type: "datetime-local"}, id:"jmfc_registration_date" },
    { type: "input", label: "CNR Number", props: { type: "text"}, id:"cnr_no" },
    { type: "input", label: "Case Title", props: { type: "text" }, id:"jmfc_case_title" },
    { type: "input", label: "Name of Court", props: { type: "text"}, id:"name_of_jmfc_court" },
    { type: "input", label: "First Hearing Date", props: { type: "date" }, id:"first_hearing_date" },
    { type: "input", label: "Decided on /Fixed For", props: { type: "date"}, id:"decided_on" },
  ],
  MACT_court_details: [
    { type: "input", label: "MACT Court", props: { type: "text"}, id:"mact_cl" },
    { type: "input", label: "Claim Amount", props: { type: "text" }, id:"claim_amount" },
    { type: "input", label: "Claim Filled U/S", props: { type: "text" }, id:"claim_filled_us" },
  ],
  policy_details: [
    { type: "radio", label: "Is policy Genuine", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }],id:"policy_genuine" },
    { type: "input", label: "Policy Number", props: { type: "text" }, id: "policy_no" },
    { type: "input", label: "Policy Type", props: { type: "text" }, id: "policy_type" },
    { type: "input", label: "Risk Inception Date", props: { type: "date-time" }, id:"policy_start_date" },
    { type: "input", label: "Risk End Date", props: { type: "date-time" }, id:"policy_end_date" },
    { type: "input", label: "IV Make", props: { type: "text" }, id:"iv_make" },
    { type: "input", label: "IV Model", props: { type: "text" }, id:"iv_model" },
    { type: "input", label: "IV IDV", props: { type: "text" }, id:"iv_idv" },
    { type: "input", label: "Vehicle Registration Year", props: { type: "date" }, id:"vehicle_registration_year" },
    { type: "radio", label: "Rollover", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"rollover" },
    { type: "radio", label: "Renewal", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"renewal" },
    { type: "radio", label: "Break-in", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"break_in" },
    { type: "input", label: "Close Proximity", props: { type: "text" } , id:"close_proximity"},
    { type: "input", label: "Previous Policy Type", props: { type: "text" }, id: "previous_policy_type" },
    { type: "input", label: "Previous Risk Inception Date", props: { type: "date" }, id:"previous_policy_start_date" },
    { type: "input", label: "Previous Risk End Date", props: { type: "date-time" }, id:"previous_policy_end_date" },
  ],
  OD_claim_details: [
    { type: "select", label: "OD reported", options: [{ value: "Yes", label: "Yes" }, { value: "No", label: "No" }, { value: "Not_Applicable", label: "Not Applicable" }],id: "od_report" },
    { type: "input", label: "OD Claim Number", props: { type: "text" }, id:"od_claim_number", dependsOn: true },
    { type: "input", label: "Date of Loss", props: { type: "datetime-local" }, id:"date_of_loss", dependsOn: true },
    { type: "input", label: "Loss Location", props: { type: "text" }, id:"loss_location", dependsOn: true },
    { type: "input", label: "Driver in the OD Claim", props: { type: "text" }, id:"driver_in_the_od_claim", dependsOn: true },
    { type: "select", label: "Claim Status", options: [{ value: "Settled", label: "Settled" }, { value: "reputed", label: "Reputed" }, { value: "Substandard", label: "Substandard" }], id:"claim_status", dependsOn: true },
    { type: "input", label: "Reputed", props: { type: "text" }, id:"reputed", dependsOn: true },
    { type: "input", label: "Sub Standard", props: { type: "text" }, id:"sub_standerd", dependsOn: true },
  ],
  insured_details: [
    { type: "select", label: "Insured Available", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"insured_available" },
    { type: "input", label: "Name of Insured", props: { type: "text" }, id:"insured", dependsOn: true },
    { type: "input", label: "Address of Insured", props: { type: "text" }, id:"insured_address", dependsOn: true },
    { type: "input", label: "Mobile Number of Insured", props: { type: "text" }, id:"mobile_no_of_insured", dependsOn: true },
    { type: "input", label: "Version of the Insured in relation to the loss", props: { type: "text" }, id:"version_of_the_insured_in_relation_to_the_loss", dependsOn: true },
    { type: "input", label: "Drive Name mentioned by Insured", props: { type: "text" }, id:"driver_name_mentioned_by_insured", dependsOn: true },
    { type: "input", label: "KYC submitted", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"kyc_submitted", dependsOn: true },
    { type: "radio", label: "ID No", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"id_no", dependsOn: true },
    { type: "input", label: "Issuing Authority", props: { type: "text" }, id:"issuing_authority", dependsOn: true },
    { type: "input", label: "Remarks by FOS ", props: { type: "text" }, id:"remark_by_fos", dependsOn: true },
    { type: "input", label: "Observation and Findings", props: { type: "text" }, id:"observation_and_findings_insured_details", dependsOn: true },
  ],
  insured_vehicle_details: [
    { type: "input", label: "Name of Owner as per RC", props: { type: "text" }, id:"owner_as_per_rc" },
    { type: "input", label: "Registration Date", props: { type: "datetime-local" }, id:"vehical_registration_date" },
    { type: "input", label: "Make of IV", props: { type: "text" }, id:"make_of_iv" },
    { type: "input", label: "Moel of IV", props: { type: "text" }, id:"moel_of_iv" },
    { type: "input", label: "Color of IV", props: { type: "text" }, id:"color_of_iv" },
    { type: "radio", label: "Permit extract copy availble", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"permit_extract_copy_availble" },
    { type: "input", label: "Permit Number", props: { type: "text" }, id:"permit_number" },
    { type: "input", label: "Type of Permit", props: { type: "text" }, id:"type_of_permit" },
    { type: "input", label: "Date of Insurnce Permit", props: { type: "datetime-local" }, id:"date_of_insurnce_ermit" },
    { type: "input", label: "Date of Expiry Permit", props: { type: "datetime-local" }, id:"date_of_expiry_permit" },
    { type: "input", label: "Number of Passanger", props: { type: "text" }, id:"number_of_passanger" },
    { type: "radio", label: "Is Vehicle Loaded", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"is_vehicle_loaded" },
    { type: "input", label: "IV reg Number as per Petition", props: { type: "text" }, id:"iv_reg_number_as_per_petition" },
    { type: "input", label: "IV reg Number as per FIR", props: { type: "text" }, id:"iv_reg_number_as_per_fir" },
    { type: "input", label: "IV reg Number as per Spot Punchnama", props: { type: "text" }, id:"iv_reg_number_as_per_spot_punchnama" },
    { type: "input", label: "Fitness Certificate Available", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"fitness_certificate_available" },
    { type: "input", label: "Fitness Validity", props: { type: "text" } },
    { type: "textarea", label: "FOS Remarks", props: { rows: 1 }, id:"fos_remark_insured_vehicle_details" },
    { type: "textarea", label: "Observation and Findings", props: { rows: 2 }, id:"observation_and_findings" },
  ],
  IV_driver_details: [
    { type: "select", label: "Driver Available", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"driver_available" },
    { type: "input", label: "Name of the IV driver", props: { type: "text" }, id:"driver", dependsOn: true },
    { type: "input", label: "Address of the IV driver", props: { type: "text" }, id:"driver_address", dependsOn: true },
    { type: "input", label: "Mobile Number of IV Driver", props: { type: "tel" }, id:"driver_mobile_no", dependsOn: true },
    { type: "input", label: "Version of the Driver in relation to the loss", props: { type: "text" }, id:"driver_version_relation_to_loss", dependsOn: true },
    { type: "input", label: "Driver’s relationship with Insured / Owner", props: { type: "datetime-local" }, id:"driver_relation_with_insured", dependsOn: true },
    { type: "input", label: "KYC submitted", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"kyc_submitted", dependsOn: true },
    { type: "input", label: "Issuing Authority", props: { type: "text" }, id:"issuing_authority", dependsOn: true },
    { type: "textarea", label: "Remarks", props: { rows: 2, required: true } }
  ],
  TPV_details: [
    { type: "select", label: "Third Party Vehicle Details Available", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"tpv_details_available" },
    { type: "input", label: "Vehicle Registration No of TPV", props: { type: "text" }, dependsOn: true, id:"tpv_reg_no" },
    { type: "radio", label: "RC Particular of TPV obtained", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], dependsOn: true, id:"tpv_rc_obtained" },
    { type: "input", label: "Name of TPV owner as per RC", props: { type: "text" }, dependsOn: true, id:"tpv_owner_name" },
    { type: "input", label: "Registration Date of TPV", props: { type: "datetime-local" }, dependsOn: true, id:"tpv_registration_date" },
    { type: "input", label: "Make of TPV", props: { type: "text" }, dependsOn: true, id:"tpv_make" },
    { type: "input", label: "Model of TPV", props: { type: "text" }, dependsOn: true , id:"tpv_model"},
    { type: "input", label: "Colour of TPV", props: { type: "text" }, dependsOn: true, id:"tpv_colour" },
    { type: "input", label: "Policy No of TPV", props: { type: "text" }, dependsOn: true, id:"tpv_policy_no" },
    { type: "input", label: "Policy Inception date of TPV", props: { type: "datetime-local" }, dependsOn: true, id:"tpv_policy_inception_date" },
    { type: "input", label: "Policy expiry date of TPV", props: { type: "datetime-local" }, dependsOn: true, id:"policy_expiry_date_tpv" }, // Corrected this line
    { type: "input", label: "Insurance company of TPV", props: { type: "text" }, dependsOn: true, id:"tpv_insurance_company" },
    { type: "textarea", label: "Remark", props: { rows: 2 }, id:"remark_tpv_details" },
  ],
  TPV_driver_Details: [
    { type: "select", label: "TPV DRIVER Details Availble", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"tpv_driver_details_available" },
    { type: "input", label: "Name of TPV Driver", props: { type: "text" }, dependsOn: true, id:"tpv_driver_name" },
    { type: "input", label: "DL No of TPV Driver", props: { type: "text" }, dependsOn: true, id:"dl_no_of_tpv_driver" },
    { type: "radio", label: "DL extractof TPV Driver obtained", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], dependsOn: true, id:"dl_extract_of_tpv_driver_obtained" },
    { type: "textarea", label: "Remarks", props: { rows: 2 }, dependsOn: true, id:"remark_tpv_driver_details" },
  ],
  MVI_report: [
    { type: "select", label: "MVI report available", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id:"mvi_report_available", dependsOn: true },
    { type: "input", label: "IV Date of Inspection", props: { type: "datetime-local" }, id:"iv_date_of_inspection", dependsOn: true },
    { type: "input", label: "MVI Report prepared By", props: { type: "text" }, id:"mvi_report_prepared_by", dependsOn: true },
    { type: "input", label: "Observation on the damages to the vehicle by the MVI Expert", props: { type: "text" }, id:"observation_by_the_mvi_expert", dependsOn: true },
    { type: "input", label: "Damages to vehicle corroborated with the accident", props: { type: "text" }, id:"damages_vehicle_corroborated_with_accident", dependsOn: true },
    { type: "textarea", label: "Observation and Findings", props: { rows: 2 }, id:"remark_mvi_report" },
  ],
  spot_Punchnama: [
    { type: "input", label: "Date and Time of Punchnama", props: { type: "datetime-local" }, id:"date_and_time_of_punchnama" },
    { type: "radio", label: "Whether IV Identified in Spot Panchanama?", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }] },
    { type: "input", label: "Names of the witnesses on whose evidence spot sketch was prepared", props: { type: "text" } },
    { type: "radio", label: "Whether spot investigation conducted by investigator?", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], required: true },
    { type: "input", label: "Date of spot investigation by investigator", props: { type: "datetime-local" } },
    { type: "input", label: "Latitude", props: { type: "text" } },
    { type: "input", label: "Longitude", props: { type: "text" } },
    { type: "input", label: "The versions of the spot witnesses", props: { type: "text" } },
    { type: "radio", label: "Whether the witnesses were named in the police records", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }] },
    { type: "radio", label: "Whether the accident had occurred under jurisdiction of NHAI", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }] },
    { type: "radio", label: "Whether any witnesses of the accident could be identified at the spot", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }] },
    { type: "radio", label: "Whether any record of the accident was captured by the NHAI", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }] },
    { type: "input", label: "Distance of the first treating hospital from the spot of accident", props: { type: "text" } },
    { type: "input", label: "Important Landmark near the spot of accident", props: { type: "text" } },
    { type: "textarea", label: "Remarks", props: { rows: 2 }, required: true },
  ],
  claimant_victim_details: [
    { type: "select", label: "Claimant / Victim Met", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }],id:"claimant_victim_met" },
    { type: "input", label: "Name of the Claimant", props: { type: "text" }, id:"name_of_claimant", dependsOn: true },
    { type: "input", label: "Address of the claimant", props: { type: "text" }, id:"address_of_claimant", dependsOn: true },
    { type: "input", label: "Relationo of the Victim With Claimant", props: { type: "text"}, id:"relationo_of_victim_with_claimant", dependsOn: true },
    { type: "input", label: "Name of the Injured", props: { type: "text"}, id:"name_of_injured", dependsOn: true },
    { type: "input", label: "Name of the Deceased", props: { type: "text" }, id:"name_of_deceased", dependsOn: true },
    { type: "input", label: "Age of the Deceased as per petition", props: { type: "number" }, id:"age_of_deceased_per_petition", dependsOn: true },
    { type: "input", label: "Age of the Deceased as per Age proof", props: { type: "number" }, id:"age_of_deceased_per_age_proof", dependsOn: true },
    { type: "input", label: "Marital Status", options: [{ value: "Single", label: "Single" }, { value: "Married", label: "Married" }], id:"marital_status", dependsOn: true },
    { type: "input", label: "Claimant version in relation with the loss", props: { type: "text" }, id:"claimant_version_relation_with_the_loss", dependsOn: true },
    { type: "textarea", label: "Observation and Finding", props: { rows: 2 }, id:"remark_claimant_victim_details" }
  ],
  seizure_details: [
    { type: "select", label: "Seizure Memo available", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], props: { required: true }, id:"seizure_available" },
    { type: "input", label: "Date of Seizing", props: { type:"datetime-local" }, id:"date_of_seizing", dependsOn: true },
    { type: "input", label: "Delay in seizure (days)", props: { type: "input" }, id:"delay_in_seizure", dependsOn: true },
    { type: "input", label: "Date on which the vehicle documents were seized", props: { type: "datetime-local"}, id:"date_on_which_vehical_seized", dependsOn: true },
    { type: "input", label: "Name of person who had produced the vehicle documents to the Police", props: { type: "text" }, id:"person_who_produce_vehical_documents", dependsOn: true },
    { type: "textarea", label: "Observation and Findings", props: { type: "text" }, id:"observation_and_findings_seizure_details" },
  ],
  fir_details: [
    { type: "input", label: "FIR Number", props: { type: "text" }, id: "fir_no" },
    { type: "input", label: "Name of the Police station", props: { type: "text" }, id: "police_station" },
    { type: "input", label: "Police station city/District", id: "police_station_district" },
    { type: "input", label: "Police station tehsil", props: { type: "text" }, id: "police_station_tehsil" },
    { type: "input", label: "Date of FIR", props: { type: "datetime-local" }, id: "fir_date" },
    { type: "input", label: "Section IPC & MV act", props: { type: "text" }, id: "ipc_mv_section" },
    { type: "input", label: "Date of Accident", props: { type: "datetime-local" }, id: "date_of_loss" },
    { type: "textarea", label: "Place of accident", props: { rows: 2 }, id: "loss_location" },
    { type: "input", label: "Delay in FIR (days)", props: { type: "datetime-local" }, id: "delayInFir" },
    { type: "input", label: "Reasons for delay", props: { type: "text" }, id: "fir_delay_reason" },
    { type: "input", label: "Name of the complainant", props: { type: "text" }, id: "complainant_name" },
    { type: "input", label: "Relationship of the complainant with injured/deceased", props: { type: "text" }, id: "complainant_relationship" },
    { type: "input", label: "Registration No. of the offending vehicle's as per FIR", props: { type: "text" }, id: "offending_vehicle_registration" },
    { type: "input", label: "Registration no. of other vehicles (TPV)", props: { type: "text" }, id: "tpv_registration" },
    { type: "input", label: "Name of injured/deceased as per the FIR", props: { type: "text" }, id: "injured_name_fir" },
    { type: "input", label: "Name of the accused", props: { type: "text" }, id: "accused_name" },
    { type: "input", label: "Filed Against", props: { type: "text" }, id: "filed_against" },
    { type: "textarea", label: "FIR version of the Complainant", props: { rows: 3 }, id: "fir_version_complainant" }
  ],
  tp_vehicle_details: [
    { type: "input", label: "Vh No of the TP", props: { type: "text" }, id: "tp_vehicle_no" },
    { type: "select", label: "RC Particular of TPV obtained", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id: "tp_rc_obtained" },
    { type: "input", label: "Name of TPV owner as per RC", props: { type: "text" }, id: "tp_owner_name" },
    { type: "input", label: "Registration Date of TPV", props: { type: "date" }, id: "tp_registration_date" },
    { type: "input", label: "Make of TPV", props: { type: "text" }, id: "tp_make" },
    { type: "input", label: "Model of TPV", props: { type: "text" }, id: "tp_model" },
    { type: "input", label: "Colour of TPV", props: { type: "text" }, id: "tp_colour" },
    { type: "input", label: "Policy No of TPV", props: { type: "text" }, id: "tp_policy_no" },
    { type: "input", label: "Policy Inception date of TPV", props: { type: "date" }, id: "tp_policy_inception_date" },
    { type: "input", label: "Policy expiry date of TPV", props: { type: "date" }, id: "tp_policy_expiry_date" },
    { type: "select", label: "Insurance company of TPV", options: [{ value: "Yes", label: "Yes" }, { value: "no", label: "No" }], id: "tp_insurance_company" },
    { type: "textarea", label: "FOS Remarks", props: { rows: 2 }, id: "fos_remarks" }
  ],
  treatment_details: [
      { type: "input", label: "Name of the Victim", props: { type: "text" }, id: "victim_name" },
      { type: "input", label: "MLC Number", props: { type: "text" }, id: "mlc_number" },
      { type: "input", label: "Date & Time of MLC", props: { type: "datetime-local" }, id: "mlc_date_time" },
      { type: "input", label: "MLC Raised by", props: { type: "text" }, id: "mlc_raised_by" },
      { type: "input", label: "Whether victim was admitted in more than 1 hospital", props: { type: "text" }, id: "multiple_hospitals" },
      { type: "input", label: "1st Treating Hospital Name", props: { type: "text" }, id: "first_hospital_name" },
      { type: "textarea", label: "1st Treating Hospital Address", props: { rows: 2 }, id: "first_hospital_address" },
      { type: "input", label: "2nd Treating Hospital Name", props: { type: "text" }, id: "second_hospital_name" },
      { type: "textarea", label: "2nd Treating Hospital Address", props: { rows: 2 }, id: "second_hospital_address" },
      { type: "input", label: "Brought By", props: { type: "text" }, id: "brought_by" },
      { type: "input", label: "How the victim was brought to the hospital", props: { type: "text" }, id: "victim_transport_method" },
      { type: "textarea", label: "Cause of accident as per MLC", props: { rows: 2 }, id: "accident_cause" },
      { type: "input", label: "Has the victim suffered any kind of disability", props: { type: "text" }, id: "disability" },
      { type: "select", label: "Type of hospital/institute issuing disability certificate", options: [{value:"Govt Hospital", label:"Govt Hospital"}, {value:"Private Hospital", lable:"Private Hospital"}], id: "disability_certificate_hospital" },
      { type: "input", label: "Date & Time of Admission", props: { type: "datetime-local" }, id: "admission_date_time" },
      { type: "input", label: "Date of Discharge", props: { type: "date" }, id: "discharge_date" },
      { type: "input", label: "Date of Death", props: { type: "date" }, id: "death_date" },
      { type: "input", label: "Name of Treating Doctor", props: { type: "text" }, id: "treating_doctor" }
  ]
};