export const registration_data = {
    date_of_loss: "",
    petitioners: [{ name: "" }],
    petitioner_address: "",
    petitioner_district: "",
    petitioner_tehsil: "",
    insured: "",
    insured_address: "",
    insured_district: "",
    insured_tehsil: "",
    driver: "",
    loss_location: "",
    driver_address: "",
    driver_district: "",
    driver_tehsil: "",
    insurer: "",
    state: "",
    email_id: "",
    assigned_by: "",
    case_type: "",
    claim_no: "",
    mact_case_no: "",
    ir_status: "",
    task: "",
    fosAssignments: [{ fos: "", tasks: [] }],
    mact_cl: "",
    policy_no: "",
    dl_no: "",
    iv_no: "",
    iv_type: "",
    product_code: "",
    type_of_loss: "",
    injured_name: "",
    doa: "",
    fir_no: "",
    fir_date: "",
    police_station: "",
    delayInFir: 0,
    police_station_address: "",
    police_station_district: "",
    police_station_tehsil: "",
    petitionerStatus: "", // Yes, No, Not Required
    insuredStatus: "", // Yes, No, Not Required
    driverStatus: "", // Yes, No, Not Required
    petitionerJustification: "",
    insuredJustification: "",
    driverJustification: "",
    claim_amount: "",
    claim_filled_us: "",
    policy_start_date: "",
    policy_end_date: "",
  };