export const district_filters = [
    { value: "ahmednagar", label: "Ahmednagar" },
    { value: "akola", label: "Akola" },
    { value: "amravati", label: "Amravati" },
    { value: "aurangabad", label: "Aurangabad" },
    { value: "beed", label: "Beed" },
    { value: "bhandara", label: "Bhandara" },
    { value: "buldhana", label: "Buldhana" },
    { value: "chandrapur", label: "Chandrapur" },
    { value: "dhule", label: "Dhule" },
    { value: "gadchiroli", label: "Gadchiroli" },
    { value: "gondia", label: "Gondia" },
    { value: "hingoli", label: "Hingoli" },
    { value: "jalgaon", label: "Jalgaon" },
    { value: "jalna", label: "Jalna" },
    { value: "kolhapur", label: "Kolhapur" },
    { value: "latur", label: "Latur" },
    { value: "mumbai_city", label: "Mumbai City" },
    { value: "mumbai_suburban", label: "Mumbai Suburban" },
    { value: "nagpur", label: "Nagpur" },
    { value: "nanded", label: "Nanded" },
    { value: "nandurbar", label: "Nandurbar" },
    { value: "nasik", label: "Nasik" },
    { value: "osmanabad", label: "Osmanabad" },
    { value: "parbhani", label: "Parbhani" },
    { value: "pune", label: "Pune" },
    { value: "raigad", label: "Raigad" },
    { value: "ratnagiri", label: "Ratnagiri" },
    { value: "sangli", label: "Sangli" },
    { value: "satara", label: "Satara" },
    { value: "sindhudurg", label: "Sindhudurg" },
    { value: "solapur", label: "Solapur" },
    { value: "thane", label: "Thane" },
    { value: "wardha", label: "Wardha" },
    { value: "washim", label: "Washim" },
    { value: "yavatmal", label: "Yavatmal" }
];
