export const citieLists = [
    "Ahmednagar",
    "Akola",
    "Alibag",
    "Amravati",
    "Aurangabad",
    "Baramati",
    "Beed",
    "Bhandara",
    "Bhiwandi",
    "Bhusawal",
    "Chandrapur",
    "Dhule",
    "Dombivli",
    "Gondia",
    "Hingoli",
    "Ichalkaranji",
    "Jalgaon",
    "Jalna",
    "Karad",
    "Kolhapur",
    "Latur",
    "Malegaon",
    "Mira-Bhayandar",
    "Mumbai",
    "Nagpur",
    "Nanded",
    "Nashik",
    "Navi Mumbai",
    "Osmanabad",
    "Palghar",
    "Panvel",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Solapur",
    "Thane",
    "Vasai-Virar",
    "Wardha",
    "Washim",
    "Yavatmal"
];

// const models= {
//     citieLists
// }
// export default models;