stages:
  - fmt
  - validate
  - plan
  - apply
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - cd terraform
  - rm -rf .terraform
  - terraform --version
  - terraform init
  
fmt:
  stage: fmt
  script:
    - terraform fmt -check=true

validate:
  stage: validate
  script:
    - terraform validate


plan:
  stage: plan
  script:
    - terraform plan
  dependencies:
    - fmt
    - validate
  only:
    - merge_requests


apply:
  stage: apply
  script:
    - terraform plan -out=plan_output.tfplan
    - terraform apply -input=false "plan_output.tfplan"
  dependencies:
    - plan
  only:
    - main
  when: manual